### ISSUE TITLE
Continuous loading string library

### ISSUE THREAD

**Issue by Nighthawk1207** [ElbowBaggins/GinsorAudioTool2Plus#10]
![image](https://user-images.githubusercontent.com/20056785/154815115-818151c7-a285-4488-a17c-f3a9d772ef70.png)

String database continuously loading, completes then repeats. Happens on initial startup.

**Comment by Nighthawk1207** [comment]
Narrowed down to these pkg files not existing in the game files.
```
w64_environments_01a9_0.pkg
w64_orphaned_0901_0.pkg
w64_sandbox_08a6_0.pkg
w64_shared_manifest_08a5_0.pkg
w64_shared_manifest_0900_0.pkg
```

Attempted to bypass these files in code, achieved that. After which no files were playing or loading their transcripts properly.

**Comment by ElbowBaggins** [comment]
#9 - See my comments here, it is related.

This cannot be fixed until that underlying issue is rectified or the required data is found elsewhere.

Sorry, I'm pretty chapped by it too.
