### ISSUE TITLE
"Generating string database"

### ISSUE THREAD

**Issue by Cont0rt** [ElbowBaggins/GinsorAudioTool2Plus#15]
Whenever I try opening the executable with the program, it just shows this constantly. I've left it for an entire day and it just keeps doing it. Am I doing anything wrong? Or is it just broken?

![image](https://user-images.githubusercontent.com/106750807/183370251-461f2983-838a-4831-89d8-9d9147971bd8.png)

**Comment by ElbowBaggins** [comment]
It's long broken. This is the same issues as #7 and #12.

I _am_ looking at these but only when I have free time and want to look at Ginsor's original code, which hasn't been horribly often.

It's fix_able_ (and I do have a build that detects all strings but is still failing to build the audio database, so progress has been made) but I wouldn't expect this soon. Destiny's package format has been in much more flux lately than ever before. At one point, this tool reliably worked across Destiny updates but this is simply no longer the case.
