### ISSUE TITLE
Need .NET Framework, yet it's installed.

### ISSUE THREAD

**Issue by Potatoified** [ElbowBaggins/GinsorAudioTool2Plus#17]
I have .NET Framework installed but whenever I try to launch Ginsor it tells me that I need to install it, I press "ok" to install and it does nothing.
![image](https://user-images.githubusercontent.com/40216635/212195036-3a761f03-e2fb-4bef-805d-48684ae0c7e4.png)
![image](https://user-images.githubusercontent.com/40216635/212195160-799f0f4e-9278-4de4-9350-afa7d584c7af.png)

**Comment by ElbowBaggins** [comment]
That's... weird. _I_ didn't write that in, I assume that has to be some kind of inbuilt .NET behaviour that's gone haywire.

Regardless, even if you got it to run, it doesn't actually work on the current form of Destiny 2's `.pkg` files. It is, technically, possible to fix, but Ginsor's original implementation is _very_ spaghetti so it's _kiiiiiinda_ not worth it.

You'd probably have better luck with one of the several _other_ Destiny 2 package extractors out there. You can dig through the other issues on this project (and its forks) to see why. I just keep it online as a historical oddity (and idk maybe I'll fix it one day)
