### ISSUE TITLE
Needs Update

### ISSUE THREAD

**Issue by rootbeer23** [ElbowBaggins/GinsorAudioTool2Plus#2]
Hopefully you will be updating for after Beyond Light compatibility?

**Comment by KaneTW** [comment]
I'll submit a PR in a moment. Cracked the encryption after a long-ass time (turns out I was too cautious and the true decryption key requires a network connection).

**Comment by KaneTW** [comment]
A "moment" might take a while. Not only did the encryption and .pkg format change, but apparently also where the strings are stored. Not sure if I'll have the time for it, but let's see.

**Comment by KaneTW** [comment]
PR #3 fixes this :)

**Comment by MrSalta** [comment]
@KaneTW does your repo have a compiled release version?

**Comment by KaneTW** [comment]
yes, check releases

**Comment by ElbowBaggins** [comment]
Merged fix.
