### ISSUE TITLE
support other Language.

### ISSUE THREAD

**Issue by no117** [ElbowBaggins/GinsorAudioTool2Plus#4]
Hi. I'm a Korean Destiny user.
First, I wrote it using a translator. I'm sorry, but please understand.
I used Audio Tool v1 until the first week of the release of Beyond the Light, but it no longer works and I was looking for another tool, and I found your file. However, It doesn't support Korean, so I'm looking for another way, but after looking at your reply left by [reddit](https://www.reddit.com/r/raidsecrets/comments/k5bcyz/i_updated_ginsors_audio_tool_for_beyond_light/) to Syscache, I knew there was a way.
But, I can't understand how to do it. Could you please let me know, if this is the way I can do it?

**Comment by krepe-suZette** [comment]
https://github.com/krepe-suZette/GinsorAudioTool2Plus/tree/korean-y4

한국어 음성 + 텍스트가 나오도록 코드를 수정했습니다. 다만 일부 텍스트가 정상적으로 보이지 않는 경우가 있네요.
I modified the code to show Korean voice and text. However, there are some cases where some text does not look normal.

**Comment by ElbowBaggins** [comment]
I probably won't fix this in this version any time soon, a Rust rewrite is in the the tubes which will support the desired behavior intrinsically. I would be happy to accept any PRs though.
