### ISSUE TITLE
Still broken and DCV is about to consume more

### ISSUE THREAD

**Issue by RumekFuria** [ElbowBaggins/GinsorAudioTool2Plus#9]
ok look m8.
yes I shoudn't be making this issue since the other one exists
but I have to at least get some answer in some way. 
you said it yourself.
"A minor fix"
yet an entire season and a half has passed, still broken.
DCV is happening, half of Forsaken is being removed.
**this** is the only tool of this kind that would allow people to easily archive sound files before they dissapear forever

all I ask for is any kind of answer. of course I hope the answer will be "yes yes fixing it" but I at least want to know should I just wait, or start seeking places to fix it myself/have someone else fix it. at least leave some compilation instructions in the readme for anyone wanting to dabble in this mess themselves

**Comment by ElbowBaggins** [comment]
Duplicate of #7
